language: node_js
node_js:
  - "8"
  - "9"
install:
  - npm install
script:
  - npm run build
  - npm run eslint
  - npm run csscomb
branches:
  only:
    - master
    - /^dev/.*$/
    - /^hotfix/.*$/
    - /^greenkeeper/.*$/